### PR TITLE
Update structure to Phoenix 1.3

### PR DESCRIPTION
**Pull request by whatyouhide**
This was hard 😄 I definitely struggle with JS and have only worked with JSON APIs + Phoenix, no assets stuff basically. I managed to make it work though, changing the structure to `lib/chat_web/` and updating everything else.

@chrismccord would appreciate your input though :P

### CODE REVIEW

**Comment by chrismccord** [comment]
@whatyouhide sorry I was behind getting to this! Can you reopen?

**Comment by whatyouhide** [comment]
Oh boy sorry, I was cleaning up PRs and got too easy triggered on this :) I'll open new PR when at the computer as it won't let me open this one.

**Comment by whatyouhide** [comment]
@chrismccord I just had to restore the branch! Here you go :D

**Comment by whatyouhide** [comment]
This is outdated now that Phoenix 1.4 is out, so @chrismccord if you're ok with it, I'm gonna close this one! :) Let me know if you could still find value in this and I'll reopen right away.

**Pull request closed without merging**
